config/routes.rb
Rails.application.routes.draw do
  root "home#index"             # Главная
  get "news", to: "news#index"   # Новости 
  get "home/index"
  

  namespace :api, defaults: { format: :json } do  # Пространство имён для API
    resources :products, only: [:index, :create, :destroy, :update]    # Маршруты для продуктов
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  
  validates :name, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
  before_action :authenticate_api_key
  protect_from_forgery with: :null_session
  
  def index
    products = Product.all

    products = products.where("name LIKE ?", "%#{params[:name]}%") if params[:name].present? # Фильтрация по имени 

    products = products.where("price >= ?", params[:min_price]) if params[:min_price].present? # Фильтрация по цене 
    products = products.where("price <= ?", params[:max_price]) if params[:max_price].present?

    products = products.page(params[:page]).per(params[:per_page] || 5) # Пагинация

    render json: products
  end

  def create
    puts "==== CREATE CALLED ===="
    product = Product.new(product_params)
    if product.save
      render json: product, status: :created
    else
      render json: { errors: product.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    product = Product.find_by(id: params[:id])
    if product
      product.destroy
      render json: { message: "Product deleted successfully" }, status: :ok
    else
      render json: { error: "Product not found" }, status: :not_found
    end
  end

  def update
  product = Product.find_by(id: params[:id])
  if product
    if product.update(product_params)
      render json: product, status: :ok
    else
      render json: { errors: product.errors.full_messages }, status: :unprocessable_entity
    end
  else
    render json: { error: "Product not found" }, status: :not_found
  end
end

  private

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  private

  def authenticate_api_key
    unless params[:api_key] == Rails.application.config.api_key
      render json: { error: "Unauthorized" }, status: :unauthorized
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
end

  def about
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/helpers/api/products_helper.rb
module Api::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/index.html.erb
<div class="centered">
  <h1 style="font-size: 48px; text-transform: uppercase;">News</h1>
   <nav style="margin: 20px 0;">
    <%= link_to "Home", root_path, class: "button" %>
    <%= link_to "News", news_path, class: "button green" %>
  </nav>
  <p>Here will be our news section! 📰</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Навигация сайта -->
    <nav>
      <%= link_to "Home", root_path %> <!-- Ссылка на главную страницу -->
      |
      <%= link_to "News", news_path %> <!-- Ссылка на страницу Новости -->
      </nav>

      <%= yield %> <!-- Здесь выводится содержимое страниц -->
      </body>
      </html>

app/views/news/index.html.erb
<h1>News#index</h1>
<p>Find me in app/views/news/index.html.erb</p>